# docker-compose -f elasticsearch7-2nodes-cerebro-docker-compose.yml up -d
version: '3.1'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.5
    container_name: 'eck7_cerebro'
    ports:
      - 19201:9000
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - eck7
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: 'eck7_kibana7'
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED=true
    ports:
      - 15601:5601
    networks:
      - eck7
  elasticsearch:
    image: elasticsearch:7.5.1
    container_name: 'eck7_elasticsearch_01'
    environment:
      - cluster.name=geektime
      - node.name=eck7_elasticsearch_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=eck7_elasticsearch_01
      - cluster.initial_master_nodes=eck7_elasticsearch_01,eck7_elasticsearch_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data1:/usr/share/elasticsearch/data
    ports:
      - 19210:9200
    networks:
      - eck7
  elasticsearch2:
    image: elasticsearch:7.5.1
    container_name: 'eck7_elasticsearch_02'
    environment:
      - cluster.name=geektime
      - node.name=eck7_elasticsearch_02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=eck7_elasticsearch_01
      - cluster.initial_master_nodes=eck7_elasticsearch_01,eck7_elasticsearch_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data2:/usr/share/elasticsearch/data
    ports:
      - 19220:9200
    networks:
      - eck7

volumes:
  es7data1:
    driver: local
  es7data2:
    driver: local

networks:
  eck7:
    driver: bridge
