services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_LICENSE_ACTIVATION_KEY=enterprise-poc-key
      - N8N_LICENSE_TENANT_ID=enterprise-poc
      - N8N_LICENSE_SERVER_URL=http://localhost
      - N8N_LICENSE_OFFLINE_MODE=true